/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedRoutesRouteRouteImport } from './routes/_authenticated/routes/route'
import { Route as AuthenticatedProductsRouteRouteImport } from './routes/_authenticated/products/route'
import { Route as AuthenticatedProductionRouteRouteImport } from './routes/_authenticated/production/route'
import { Route as AuthenticatedOrdersRouteRouteImport } from './routes/_authenticated/orders/route'
import { Route as AuthenticatedNewOrderRouteRouteImport } from './routes/_authenticated/new-order/route'
import { Route as AuthenticatedInventoryRouteRouteImport } from './routes/_authenticated/inventory/route'
import { Route as AuthenticatedForecastRouteRouteImport } from './routes/_authenticated/forecast/route'
import { Route as AuthenticatedFelRouteRouteImport } from './routes/_authenticated/fel/route'
import { Route as AuthenticatedCompaniesRouteRouteImport } from './routes/_authenticated/companies/route'
import { Route as AuthenticatedClientsRouteRouteImport } from './routes/_authenticated/clients/route'
import { Route as AuthenticatedRoutesIndexRouteImport } from './routes/_authenticated/routes/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedFelIndexRouteImport } from './routes/_authenticated/fel/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedFelInvoicesRouteImport } from './routes/_authenticated/fel/invoices'
import { Route as AuthenticatedFelGenerateRouteImport } from './routes/_authenticated/fel/generate'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedOrderDetailOrderIdRouteRouteImport } from './routes/_authenticated/order-detail/$orderId/route'
import { Route as AuthenticatedInventoryNewEntryRouteRouteImport } from './routes/_authenticated/inventory/new-entry/route'
import { Route as AuthenticatedInventoryDetailEntryIdRouteRouteImport } from './routes/_authenticated/inventory-detail/$entryId/route'
import { Route as AuthenticatedEditOrderOrderIdRouteRouteImport } from './routes/_authenticated/edit-order/$orderId/route'
import { Route as AuthenticatedClientsNewClientRouteRouteImport } from './routes/_authenticated/clients/new-client/route'
import { Route as AuthenticatedClientsEditClientClientIdRouteRouteImport } from './routes/_authenticated/clients/edit-client/$clientId/route'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutesRouteRoute =
  AuthenticatedRoutesRouteRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRouteRoute =
  AuthenticatedProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRouteRoute =
  AuthenticatedProductionRouteRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRouteRoute =
  AuthenticatedOrdersRouteRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewOrderRouteRoute =
  AuthenticatedNewOrderRouteRouteImport.update({
    id: '/new-order',
    path: '/new-order',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRouteRoute =
  AuthenticatedInventoryRouteRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForecastRouteRoute =
  AuthenticatedForecastRouteRouteImport.update({
    id: '/forecast',
    path: '/forecast',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFelRouteRoute = AuthenticatedFelRouteRouteImport.update({
  id: '/fel',
  path: '/fel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRouteRoute =
  AuthenticatedCompaniesRouteRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRouteRoute =
  AuthenticatedClientsRouteRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutesIndexRoute =
  AuthenticatedRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInventoryRouteRoute,
  } as any)
const AuthenticatedFelIndexRoute = AuthenticatedFelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFelRouteRoute,
} as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesRouteRoute,
  } as any)
const AuthenticatedFelInvoicesRoute =
  AuthenticatedFelInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedFelRouteRoute,
  } as any)
const AuthenticatedFelGenerateRoute =
  AuthenticatedFelGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => AuthenticatedFelRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderDetailOrderIdRouteRoute =
  AuthenticatedOrderDetailOrderIdRouteRouteImport.update({
    id: '/order-detail/$orderId',
    path: '/order-detail/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryNewEntryRouteRoute =
  AuthenticatedInventoryNewEntryRouteRouteImport.update({
    id: '/new-entry',
    path: '/new-entry',
    getParentRoute: () => AuthenticatedInventoryRouteRoute,
  } as any)
const AuthenticatedInventoryDetailEntryIdRouteRoute =
  AuthenticatedInventoryDetailEntryIdRouteRouteImport.update({
    id: '/inventory-detail/$entryId',
    path: '/inventory-detail/$entryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditOrderOrderIdRouteRoute =
  AuthenticatedEditOrderOrderIdRouteRouteImport.update({
    id: '/edit-order/$orderId',
    path: '/edit-order/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewClientRouteRoute =
  AuthenticatedClientsNewClientRouteRouteImport.update({
    id: '/new-client',
    path: '/new-client',
    getParentRoute: () => AuthenticatedClientsRouteRoute,
  } as any)
const AuthenticatedClientsEditClientClientIdRouteRoute =
  AuthenticatedClientsEditClientClientIdRouteRouteImport.update({
    id: '/edit-client/$clientId',
    path: '/edit-client/$clientId',
    getParentRoute: () => AuthenticatedClientsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clients': typeof AuthenticatedClientsRouteRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteRouteWithChildren
  '/fel': typeof AuthenticatedFelRouteRouteWithChildren
  '/forecast': typeof AuthenticatedForecastRouteRoute
  '/inventory': typeof AuthenticatedInventoryRouteRouteWithChildren
  '/new-order': typeof AuthenticatedNewOrderRouteRoute
  '/orders': typeof AuthenticatedOrdersRouteRoute
  '/production': typeof AuthenticatedProductionRouteRoute
  '/products': typeof AuthenticatedProductsRouteRoute
  '/routes': typeof AuthenticatedRoutesRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/clients/new-client': typeof AuthenticatedClientsNewClientRouteRoute
  '/edit-order/$orderId': typeof AuthenticatedEditOrderOrderIdRouteRoute
  '/inventory-detail/$entryId': typeof AuthenticatedInventoryDetailEntryIdRouteRoute
  '/inventory/new-entry': typeof AuthenticatedInventoryNewEntryRouteRoute
  '/order-detail/$orderId': typeof AuthenticatedOrderDetailOrderIdRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/fel/generate': typeof AuthenticatedFelGenerateRoute
  '/fel/invoices': typeof AuthenticatedFelInvoicesRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/fel/': typeof AuthenticatedFelIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/routes/': typeof AuthenticatedRoutesIndexRoute
  '/clients/edit-client/$clientId': typeof AuthenticatedClientsEditClientClientIdRouteRoute
}
export interface FileRoutesByTo {
  '/clients': typeof AuthenticatedClientsRouteRouteWithChildren
  '/forecast': typeof AuthenticatedForecastRouteRoute
  '/new-order': typeof AuthenticatedNewOrderRouteRoute
  '/orders': typeof AuthenticatedOrdersRouteRoute
  '/production': typeof AuthenticatedProductionRouteRoute
  '/products': typeof AuthenticatedProductsRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/clients/new-client': typeof AuthenticatedClientsNewClientRouteRoute
  '/edit-order/$orderId': typeof AuthenticatedEditOrderOrderIdRouteRoute
  '/inventory-detail/$entryId': typeof AuthenticatedInventoryDetailEntryIdRouteRoute
  '/inventory/new-entry': typeof AuthenticatedInventoryNewEntryRouteRoute
  '/order-detail/$orderId': typeof AuthenticatedOrderDetailOrderIdRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/fel/generate': typeof AuthenticatedFelGenerateRoute
  '/fel/invoices': typeof AuthenticatedFelInvoicesRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/fel': typeof AuthenticatedFelIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/clients/edit-client/$clientId': typeof AuthenticatedClientsEditClientClientIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/clients': typeof AuthenticatedClientsRouteRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteRouteWithChildren
  '/_authenticated/fel': typeof AuthenticatedFelRouteRouteWithChildren
  '/_authenticated/forecast': typeof AuthenticatedForecastRouteRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRouteRouteWithChildren
  '/_authenticated/new-order': typeof AuthenticatedNewOrderRouteRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteRoute
  '/_authenticated/production': typeof AuthenticatedProductionRouteRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/new-client': typeof AuthenticatedClientsNewClientRouteRoute
  '/_authenticated/edit-order/$orderId': typeof AuthenticatedEditOrderOrderIdRouteRoute
  '/_authenticated/inventory-detail/$entryId': typeof AuthenticatedInventoryDetailEntryIdRouteRoute
  '/_authenticated/inventory/new-entry': typeof AuthenticatedInventoryNewEntryRouteRoute
  '/_authenticated/order-detail/$orderId': typeof AuthenticatedOrderDetailOrderIdRouteRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/fel/generate': typeof AuthenticatedFelGenerateRoute
  '/_authenticated/fel/invoices': typeof AuthenticatedFelInvoicesRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/fel/': typeof AuthenticatedFelIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/routes/': typeof AuthenticatedRoutesIndexRoute
  '/_authenticated/clients/edit-client/$clientId': typeof AuthenticatedClientsEditClientClientIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clients'
    | '/companies'
    | '/fel'
    | '/forecast'
    | '/inventory'
    | '/new-order'
    | '/orders'
    | '/production'
    | '/products'
    | '/routes'
    | '/settings'
    | '/users'
    | '/forgot-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/clients/new-client'
    | '/edit-order/$orderId'
    | '/inventory-detail/$entryId'
    | '/inventory/new-entry'
    | '/order-detail/$orderId'
    | '/errors/$error'
    | '/fel/generate'
    | '/fel/invoices'
    | '/companies/'
    | '/fel/'
    | '/inventory/'
    | '/routes/'
    | '/clients/edit-client/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clients'
    | '/forecast'
    | '/new-order'
    | '/orders'
    | '/production'
    | '/products'
    | '/settings'
    | '/users'
    | '/forgot-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/clients/new-client'
    | '/edit-order/$orderId'
    | '/inventory-detail/$entryId'
    | '/inventory/new-entry'
    | '/order-detail/$orderId'
    | '/errors/$error'
    | '/fel/generate'
    | '/fel/invoices'
    | '/companies'
    | '/fel'
    | '/inventory'
    | '/routes'
    | '/clients/edit-client/$clientId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/clients'
    | '/_authenticated/companies'
    | '/_authenticated/fel'
    | '/_authenticated/forecast'
    | '/_authenticated/inventory'
    | '/_authenticated/new-order'
    | '/_authenticated/orders'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/routes'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/clients/new-client'
    | '/_authenticated/edit-order/$orderId'
    | '/_authenticated/inventory-detail/$entryId'
    | '/_authenticated/inventory/new-entry'
    | '/_authenticated/order-detail/$orderId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/fel/generate'
    | '/_authenticated/fel/invoices'
    | '/_authenticated/companies/'
    | '/_authenticated/fel/'
    | '/_authenticated/inventory/'
    | '/_authenticated/routes/'
    | '/_authenticated/clients/edit-client/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-order': {
      id: '/_authenticated/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof AuthenticatedNewOrderRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fel': {
      id: '/_authenticated/fel'
      path: '/fel'
      fullPath: '/fel'
      preLoaderRoute: typeof AuthenticatedFelRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes/': {
      id: '/_authenticated/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AuthenticatedRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedInventoryRouteRoute
    }
    '/_authenticated/fel/': {
      id: '/_authenticated/fel/'
      path: '/'
      fullPath: '/fel/'
      preLoaderRoute: typeof AuthenticatedFelIndexRouteImport
      parentRoute: typeof AuthenticatedFelRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedCompaniesRouteRoute
    }
    '/_authenticated/fel/invoices': {
      id: '/_authenticated/fel/invoices'
      path: '/invoices'
      fullPath: '/fel/invoices'
      preLoaderRoute: typeof AuthenticatedFelInvoicesRouteImport
      parentRoute: typeof AuthenticatedFelRouteRoute
    }
    '/_authenticated/fel/generate': {
      id: '/_authenticated/fel/generate'
      path: '/generate'
      fullPath: '/fel/generate'
      preLoaderRoute: typeof AuthenticatedFelGenerateRouteImport
      parentRoute: typeof AuthenticatedFelRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order-detail/$orderId': {
      id: '/_authenticated/order-detail/$orderId'
      path: '/order-detail/$orderId'
      fullPath: '/order-detail/$orderId'
      preLoaderRoute: typeof AuthenticatedOrderDetailOrderIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/new-entry': {
      id: '/_authenticated/inventory/new-entry'
      path: '/new-entry'
      fullPath: '/inventory/new-entry'
      preLoaderRoute: typeof AuthenticatedInventoryNewEntryRouteRouteImport
      parentRoute: typeof AuthenticatedInventoryRouteRoute
    }
    '/_authenticated/inventory-detail/$entryId': {
      id: '/_authenticated/inventory-detail/$entryId'
      path: '/inventory-detail/$entryId'
      fullPath: '/inventory-detail/$entryId'
      preLoaderRoute: typeof AuthenticatedInventoryDetailEntryIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-order/$orderId': {
      id: '/_authenticated/edit-order/$orderId'
      path: '/edit-order/$orderId'
      fullPath: '/edit-order/$orderId'
      preLoaderRoute: typeof AuthenticatedEditOrderOrderIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new-client': {
      id: '/_authenticated/clients/new-client'
      path: '/new-client'
      fullPath: '/clients/new-client'
      preLoaderRoute: typeof AuthenticatedClientsNewClientRouteRouteImport
      parentRoute: typeof AuthenticatedClientsRouteRoute
    }
    '/_authenticated/clients/edit-client/$clientId': {
      id: '/_authenticated/clients/edit-client/$clientId'
      path: '/edit-client/$clientId'
      fullPath: '/clients/edit-client/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsEditClientClientIdRouteRouteImport
      parentRoute: typeof AuthenticatedClientsRouteRoute
    }
  }
}

interface AuthenticatedClientsRouteRouteChildren {
  AuthenticatedClientsNewClientRouteRoute: typeof AuthenticatedClientsNewClientRouteRoute
  AuthenticatedClientsEditClientClientIdRouteRoute: typeof AuthenticatedClientsEditClientClientIdRouteRoute
}

const AuthenticatedClientsRouteRouteChildren: AuthenticatedClientsRouteRouteChildren =
  {
    AuthenticatedClientsNewClientRouteRoute:
      AuthenticatedClientsNewClientRouteRoute,
    AuthenticatedClientsEditClientClientIdRouteRoute:
      AuthenticatedClientsEditClientClientIdRouteRoute,
  }

const AuthenticatedClientsRouteRouteWithChildren =
  AuthenticatedClientsRouteRoute._addFileChildren(
    AuthenticatedClientsRouteRouteChildren,
  )

interface AuthenticatedCompaniesRouteRouteChildren {
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
}

const AuthenticatedCompaniesRouteRouteChildren: AuthenticatedCompaniesRouteRouteChildren =
  {
    AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  }

const AuthenticatedCompaniesRouteRouteWithChildren =
  AuthenticatedCompaniesRouteRoute._addFileChildren(
    AuthenticatedCompaniesRouteRouteChildren,
  )

interface AuthenticatedFelRouteRouteChildren {
  AuthenticatedFelGenerateRoute: typeof AuthenticatedFelGenerateRoute
  AuthenticatedFelInvoicesRoute: typeof AuthenticatedFelInvoicesRoute
  AuthenticatedFelIndexRoute: typeof AuthenticatedFelIndexRoute
}

const AuthenticatedFelRouteRouteChildren: AuthenticatedFelRouteRouteChildren = {
  AuthenticatedFelGenerateRoute: AuthenticatedFelGenerateRoute,
  AuthenticatedFelInvoicesRoute: AuthenticatedFelInvoicesRoute,
  AuthenticatedFelIndexRoute: AuthenticatedFelIndexRoute,
}

const AuthenticatedFelRouteRouteWithChildren =
  AuthenticatedFelRouteRoute._addFileChildren(
    AuthenticatedFelRouteRouteChildren,
  )

interface AuthenticatedInventoryRouteRouteChildren {
  AuthenticatedInventoryNewEntryRouteRoute: typeof AuthenticatedInventoryNewEntryRouteRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
}

const AuthenticatedInventoryRouteRouteChildren: AuthenticatedInventoryRouteRouteChildren =
  {
    AuthenticatedInventoryNewEntryRouteRoute:
      AuthenticatedInventoryNewEntryRouteRoute,
    AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  }

const AuthenticatedInventoryRouteRouteWithChildren =
  AuthenticatedInventoryRouteRoute._addFileChildren(
    AuthenticatedInventoryRouteRouteChildren,
  )

interface AuthenticatedRoutesRouteRouteChildren {
  AuthenticatedRoutesIndexRoute: typeof AuthenticatedRoutesIndexRoute
}

const AuthenticatedRoutesRouteRouteChildren: AuthenticatedRoutesRouteRouteChildren =
  {
    AuthenticatedRoutesIndexRoute: AuthenticatedRoutesIndexRoute,
  }

const AuthenticatedRoutesRouteRouteWithChildren =
  AuthenticatedRoutesRouteRoute._addFileChildren(
    AuthenticatedRoutesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRouteRoute: typeof AuthenticatedClientsRouteRouteWithChildren
  AuthenticatedCompaniesRouteRoute: typeof AuthenticatedCompaniesRouteRouteWithChildren
  AuthenticatedFelRouteRoute: typeof AuthenticatedFelRouteRouteWithChildren
  AuthenticatedForecastRouteRoute: typeof AuthenticatedForecastRouteRoute
  AuthenticatedInventoryRouteRoute: typeof AuthenticatedInventoryRouteRouteWithChildren
  AuthenticatedNewOrderRouteRoute: typeof AuthenticatedNewOrderRouteRoute
  AuthenticatedOrdersRouteRoute: typeof AuthenticatedOrdersRouteRoute
  AuthenticatedProductionRouteRoute: typeof AuthenticatedProductionRouteRoute
  AuthenticatedProductsRouteRoute: typeof AuthenticatedProductsRouteRoute
  AuthenticatedRoutesRouteRoute: typeof AuthenticatedRoutesRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRoute
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEditOrderOrderIdRouteRoute: typeof AuthenticatedEditOrderOrderIdRouteRoute
  AuthenticatedInventoryDetailEntryIdRouteRoute: typeof AuthenticatedInventoryDetailEntryIdRouteRoute
  AuthenticatedOrderDetailOrderIdRouteRoute: typeof AuthenticatedOrderDetailOrderIdRouteRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRouteRoute: AuthenticatedClientsRouteRouteWithChildren,
  AuthenticatedCompaniesRouteRoute:
    AuthenticatedCompaniesRouteRouteWithChildren,
  AuthenticatedFelRouteRoute: AuthenticatedFelRouteRouteWithChildren,
  AuthenticatedForecastRouteRoute: AuthenticatedForecastRouteRoute,
  AuthenticatedInventoryRouteRoute:
    AuthenticatedInventoryRouteRouteWithChildren,
  AuthenticatedNewOrderRouteRoute: AuthenticatedNewOrderRouteRoute,
  AuthenticatedOrdersRouteRoute: AuthenticatedOrdersRouteRoute,
  AuthenticatedProductionRouteRoute: AuthenticatedProductionRouteRoute,
  AuthenticatedProductsRouteRoute: AuthenticatedProductsRouteRoute,
  AuthenticatedRoutesRouteRoute: AuthenticatedRoutesRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRoute,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEditOrderOrderIdRouteRoute:
    AuthenticatedEditOrderOrderIdRouteRoute,
  AuthenticatedInventoryDetailEntryIdRouteRoute:
    AuthenticatedInventoryDetailEntryIdRouteRoute,
  AuthenticatedOrderDetailOrderIdRouteRoute:
    AuthenticatedOrderDetailOrderIdRouteRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
